import RPi.GPIO as GPIO
import time, sys

GPIO.setmode(GPIO.BCM)

FRONT_LEFT_FOREWARD = 1
FRONT_LEFT_BACKWARD = 2
FRONT_RIGHT_FOREWARD = 3
FRONT_RIGHT_BACKWARD = 4
BACK_LEFT_FOREWARD = 5
BACK_LEFT_BACKWARD = 6
BACK_RIGHT_FOREWARD = 7
BACK_RIGHT_BACKWARD = 8

GPIO.setup(FRONT_LEFT_FOREWARD, GPIO.OUT)
GPIO.setup(FRONT_LEFT_BACKWARD, GPIO.OUT)
GPIO.setup(FRONT_RIGHT_FOREWARD, GPIO.OUT)
GPIO.setup(FRONT_RIGHT_BACKWARD, GPIO.OUT)
GPIO.setup(BACK_LEFT_FOREWARD, GPIO.OUT)
GPIO.setup(BACK_LEFT_BACKWARD, GPIO.OUT)
GPIO.setup(BACK_RIGHT_FOREWARD, GPIO.OUT)
GPIO.setup(BACK_RIGHT_BACKWARD, GPIO.OUT)

def forward():
    GPIO.output(FRONT_LEFT_FOREWARD, GPIO.HIGH)
    GPIO.output(FRONT_RIGHT_FOREWARD, GPIO.HIGH)
    GPIO.output(BACK_LEFT_FOREWARD, GPIO.HIGH)
    GPIO.output(BACK_RIGHT_FOREWARD, GPIO.HIGH)
    GPIO.output(FRONT_LEFT_BACKWARD, GPIO.LOW)
    GPIO.output(FRONT_RIGHT_BACKWARD, GPIO.LOW)
    GPIO.output(BACK_LEFT_BACKWARD, GPIO.LOW)
    GPIO.output(BACK_RIGHT_BACKWARD, GPIO.LOW)

def left():
    GPIO.output(FRONT_LEFT_BACKWARD, GPIO.HIGH)
    GPIO.output(FRONT_RIGHT_FOREWARD, GPIO.HIGH)
    GPIO.output(BACK_LEFT_FOREWARD, GPIO.HIGH)
    GPIO.output(BACK_RIGHT_BACKWARD, GPIO.HIGH)
    GPIO.output(FRONT_LEFT_FOREWARD, GPIO.LOW)
    GPIO.output(FRONT_RIGHT_BACKWARD, GPIO.LOW)
    GPIO.output(BACK_LEFT_BACKWARD, GPIO.LOW)
    GPIO.output(BACK_RIGHT_FOREWARD, GPIO.LOW)

def right():
    GPIO.output(FRONT_LEFT_FOREWARD, GPIO.HIGH)
    GPIO.output(FRONT_RIGHT_BACKWARD, GPIO.HIGH)
    GPIO.output(BACK_LEFT_BACKWARD, GPIO.HIGH)
    GPIO.output(BACK_RIGHT_FOREWARD, GPIO.HIGH)
    GPIO.output(FRONT_LEFT_BACKWARD, GPIO.LOW)
    GPIO.output(FRONT_RIGHT_FOREWARD, GPIO.LOW)
    GPIO.output(BACK_LEFT_FOREWARD, GPIO.LOW)
    GPIO.output(BACK_RIGHT_BACKWARD, GPIO.LOW)

def reverse():
    GPIO.output(FRONT_LEFT_BACKWARD, GPIO.HIGH)
    GPIO.output(FRONT_RIGHT_BACKWARD, GPIO.HIGH)
    GPIO.output(BACK_LEFT_BACKWARD, GPIO.HIGH)
    GPIO.output(BACK_RIGHT_BACKWARD, GPIO.HIGH)
    GPIO.output(FRONT_LEFT_FOREWARD, GPIO.LOW)
    GPIO.output(FRONT_RIGHT_FOREWARD, GPIO.LOW)
    GPIO.output(BACK_LEFT_FOREWARD, GPIO.LOW)
    GPIO.output(BACK_RIGHT_FOREWARD, GPIO.LOW)

GPIO.cleanup()